# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$LRjQxscLl24cIqktRpXEguS4MY6HVxqo1tsf68ztLaqFdt0FqJtNS
                        roles: 'ROLE_ADMIN'
                    user:
                        password: $2y$12$qq2ElHt6aWrDMz.9oajLduuSDfh4IL47GKpKVeMOdMkcng6fW0u/W
                        roles: 'ROLE_USER'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/api/superheroes, roles: [ROLE_ADMIN, ROLE_USER] }
