# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
#security:
#
#    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#    providers:
#        in_memory:
#            memory: ~

# app/config/security.yml
security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$12$/452DOsVB.rh1J4OOeFV..10PluYF4QusIJ2Y9ILwUyRSJoGeYHgq' #adc123
                        roles: 'ROLE_ADMIN'
                    user:
                        password: '$2y$12$i7YMW/4oc0Zdoew3iHRfJecCAOzQhdO1oL0mUw7gM71UxMqUfHbuK' #qwerty
                        roles: 'ROLE_USER'
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: homepage
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/superhero, roles: [ROLE_ADMIN, ROLE_USER ]}
