# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: 'ROLE_USER'

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$YhJG7NHjy5MQ7AEsGRjSY.YCQ.PP0Vpu.NqtQnD0bs056veiLwyki
                        roles: 'ROLE_ADMIN'
                    user:
                        password: $2y$12$5cKKP/75xu4NdNmXQK/LpehgOmAX2eXM9usD4Hc/rGC5XZI.iVuRq
                        roles: 'ROLE_USER'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                login_path: login
                check_path: login

            logout:
                path: logout
                target: homepage

    access_control:
        - { path: ^/superhero, roles: [ROLE_ADMIN, ROLE_USER] }

