# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
security:

      encoders:       #AGGIUNTO DA ME
          Symfony\Component\Security\Core\User\User:      #ALGORITMO PER CRIPTARE LE PASSWORD
               algorithm: bcrypt
               cost: 12

      role_hierarchy:
              ROLE_ADMIN:       ROLE_USER

      providers:
          in_memory:
              memory:       #MODIFICATA DA ME QUESTA PARTE
                  users:
                      admin:
                          password: $2y$12$ljgpqx10qWR2Zn837tRxGua41Vy5fBw7pExdRcYlalr1q8oaWlzOC   #password encodata tramite bash
                          roles: 'ROLE_ADMIN'
                      user:
                          password: $2y$12$j2RX796eJ2KYKiiqw8H9QOonPoRRPMjq6KlUCG9Icn9i.JSjCiIYG
                          roles: 'ROLE_USER'

      firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
         dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

         main:
            anonymous: ~            #DA QUA MESSO DA ME
            form_login:
              login_path: login
              check_path: login
            logout:
              path: logout
              target: homepage       #DOVE MI REINDIRIZZA QUANDO FACCIO IL LOGOUT (ci va il "name" della rotta)



      access_control:
           # require ROLE_ADMIN for /admin*
         - { path: ^/superhero, roles: [ROLE_ADMIN, ROLE_USER] }
            # activate different ways to authenticate




            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
