# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html

services:
    subscriber_format_exception:
        class: AppBundle\KernelSubscriber\FormatExceptionSubscriber
        tags:
            - { name: kernel.event_subscriber }

    subscriber_cors:
        class: AppBundle\KernelSubscriber\CorsSubscriber
        tags:
            - { name: kernel.event_subscriber }

    superhero_normalizer:
        class: AppBundle\Service\SuperheroNormalizer
        tags:
            - { name: serializer.normalizer }
